--- #YAML:1.0
name:               HTML-WikiConverter-Markdown
version:            0.04
abstract:           Convert HTML to Markdown markup
author:
    - David J. Iberri <diberri@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTML::Tagset:         0
    HTML::WikiConverter:  0.63
    Params::Validate:     0
    Test::More:           0
    URI:                  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
