# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-WikiConverter-Markdown
version:      0.01
version_from: lib/HTML/WikiConverter/Markdown.pm
installdirs:  site
requires:
    HTML::Tagset:                  0
    HTML::WikiConverter:           0.53
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
